const snnames=[
    "",
    "Deities",
    "Gods",
    "Kosalan",
    "Māra",
    "Nuns",
    "Brahmās",
    "Brahmins",
    "Vaṅgīsa",
    "Woods",
    "Spirits",
    "Sakka",
    "Causation",
    "Breakthrough",
    "Elements",
    "Unknowable Beginning",
    "Kassapa",
    "Gains and Honor",
    "Rāhula",
    "Lakkhaṇa",
    "Similes",
    "Monks",
    "Aggregates",
    "Rādha",
    "Views",
    "Arrival",
    "Arising",
    "Corruptions",
    "Sāriputta",
    "Dragons",
    "Phoenixes",
    "Fairies",
    "Cloud God",
    "Vacchagotta",
    "Absorption",
    "Six Sense Fields",
    "Feelings",
    "Females",
    "Jambukhādaka",
    "Sāmaṇḍaka",
    "Moggalla",
    "Citta",
    "Chiefs",
    "Unconditioned",
    "Undeclared",
    "Path",
    "Awakening Factors",
    "Mindfulness Meditation",
    "Faculties",
    "Right Efforts",
    "Five Powers",
    "Bases of Psychic Power",
    "Anuruddha",
    "Absorption",
    "Breath Meditation",
    "Stream-Entry",
    "Truths"
]
export const getFirstVaggaGroupName=(bkid,sectionname)=>{
    const i=parseInt(sectionname.slice(1));
    if (bkid.slice(0,2)=='sn') {
        return snnames[i];
    } else if (bkid.slice(0,2)=='an') {
        return 'Book of '+['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven'][i]
    }
}